version: "3.8"
services:
  mongo:
    image: mongo:6.0.5
    container_name: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - tasks-volume:/data/db
    ports:
      - "27018:27017"
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
   
volumes:
  tasks-volume:
    driver: local
  